baseURL = 'https://notes.recregt.com/'
languageCode = 'en-us'
title = 'Recregt Notes'
theme = 'PaperMod'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
pagination.pagerSize = 10
enableGitInfo = false
canonifyURLs = false

[minify]
  disableXML = true
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.css]
      precision = 2
    [minify.tdewolff.js]
      precision = 2

[params]
  mainSections = ["lessons"]
  env = "production"
  author = "Ömer Tekin"
  images = ["/images/og-image.jpg"]
  description = "University course notes, examples, and resources. Mathematics, Physics, Computer Science, and more."
  keywords = ["study notes", "university", "mathematics", "physics", "programming", "computer science"]
  DateFormat = "2 January 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true
  math = true
  # Analytics & Performance
  assets.disableHLJS = false
  assets.disableFingerprinting = false

[params.homeInfoParams]
  Title = "Welcome! 👋"
  Content = """
  I share my university course notes on this site.
  
  Explore notes for Mathematics, Physics, Computer Science, and more.
  """

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/recregt"

[[params.socialIcons]]
  name = "X"
  url = "https://x.com/recregt"

[[params.socialIcons]]
  name = "email"
  url = "mailto:me@notes.recregt.com"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/recregt"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "lessons"
  name = "Lessons"
  url = "/lessons/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "24h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "24h"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = -1
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = -1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  lessons = "/lessons/:sections[1:]/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10